# Generated by Django 4.0.6 on 2022-07-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI', models.IntegerField(verbose_name='National Physician Identifier')),
                ('Last_Name_Or_Org', models.CharField(max_length=64)),
                ('First_Name', models.CharField(max_length=64)),
                ('MI', models.CharField(blank=True, max_length=8, verbose_name='Middle Initial')),
                ('Credentials', models.CharField(max_length=128)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Entity_Type', models.CharField(choices=[('O', 'Organization'), ('I', 'Individual')], max_length=1)),
                ('Physician_Type', models.CharField(max_length=128)),
                ('MPI', models.CharField(max_length=8, verbose_name='Medicare Participation Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Total', 'Total'), ('Drug', 'Drug'), ('Medical', 'Medical')], max_length=16, null=True)),
                ('Supressed', models.CharField(blank=True, max_length=2, null=True)),
                ('HCPCS_Codes', models.IntegerField(blank=True, null=True)),
                ('Services', models.IntegerField(blank=True, null=True)),
                ('Submitted_Charges', models.FloatField(blank=True, null=True)),
                ('Mdcr_Allowed_Amt', models.FloatField(blank=True, null=True)),
                ('Mdcr_Payment_Amt', models.FloatField(blank=True, null=True)),
                ('Mdcr_Stdzd_Amt', models.FloatField(blank=True, null=True)),
                ('Physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.physician')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Benes', models.IntegerField(blank=True, null=True)),
                ('Drug_Total_Benes', models.IntegerField(blank=True, null=True)),
                ('Med_Total_Benes', models.IntegerField(blank=True, null=True)),
                ('Average_Age', models.IntegerField(blank=True, null=True)),
                ('Age_LT_65_Count', models.IntegerField(blank=True, null=True)),
                ('Age_65_74_Count', models.IntegerField(blank=True, null=True)),
                ('Age_75_84_Count', models.IntegerField(blank=True, null=True)),
                ('Age_GT_84_Count', models.IntegerField(blank=True, null=True)),
                ('Female_Count', models.IntegerField(blank=True, null=True)),
                ('Male_Count', models.IntegerField(blank=True, null=True)),
                ('Race_White_Count', models.IntegerField(blank=True, null=True)),
                ('Race_Black_Count', models.IntegerField(blank=True, null=True)),
                ('Race_API_Count', models.IntegerField(blank=True, null=True)),
                ('Race_Hispanic_Count', models.IntegerField(blank=True, null=True)),
                ('Race_NatInd_Count', models.IntegerField(blank=True, null=True)),
                ('Race_Other_Count', models.IntegerField(blank=True, null=True)),
                ('Dual_Count', models.IntegerField(blank=True, null=True)),
                ('Not_Dual_Count', models.IntegerField(blank=True, null=True)),
                ('AFib_Pct', models.FloatField(blank=True, null=True)),
                ('Alzhmr_Pct', models.FloatField(blank=True, null=True)),
                ('Asthma_Pct', models.FloatField(blank=True, null=True)),
                ('Cancer_Pct', models.FloatField(blank=True, null=True)),
                ('Heart_Failure_Pct', models.FloatField(blank=True, null=True)),
                ('Kidney_Disease_Pct', models.FloatField(blank=True, null=True)),
                ('COPD_Pct', models.FloatField(blank=True, null=True)),
                ('Depression_Pct', models.FloatField(blank=True, null=True)),
                ('Diabetes_Pct', models.FloatField(blank=True, null=True)),
                ('Hyplpdma_Pct', models.FloatField(blank=True, null=True)),
                ('Hyprtnsn_Pct', models.FloatField(blank=True, null=True)),
                ('Ischemic_Heart_Disease_Pct', models.FloatField(blank=True, null=True)),
                ('Osteoporosis_Pct', models.FloatField(blank=True, null=True)),
                ('Rh_Os_Arthritis_Pct', models.FloatField(blank=True, null=True)),
                ('Schizo_Pct', models.FloatField(blank=True, null=True)),
                ('Stroke_Pct', models.FloatField(blank=True, null=True)),
                ('Avg_Risk_Score', models.FloatField(blank=True, null=True)),
                ('Physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_Address_1', models.CharField(max_length=256)),
                ('Street_Address_2', models.CharField(blank=True, max_length=256)),
                ('City', models.CharField(max_length=128)),
                ('State', models.CharField(max_length=2)),
                ('State_FIPS', models.CharField(max_length=4)),
                ('Zip5', models.CharField(max_length=5)),
                ('RUCA', models.IntegerField()),
                ('RUCA_Desc', models.CharField(max_length=256)),
                ('Country', models.CharField(max_length=64)),
                ('Physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.physician')),
            ],
        ),
    ]
