# Generated by Django 4.0.6 on 2022-07-25 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI', models.IntegerField(verbose_name='National Provider Identifier')),
                ('Last_Name', models.CharField(max_length=64)),
                ('First_Name', models.CharField(max_length=64)),
                ('MI', models.CharField(blank=True, max_length=8, verbose_name='Middle Initial')),
                ('Credentials', models.CharField(max_length=128)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Entity_Type', models.CharField(choices=[('O', 'Organization'), ('I', 'Individual')], max_length=1)),
                ('MPI', models.CharField(max_length=8, verbose_name='Medicare Participation Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.provider')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_Address_1', models.CharField(max_length=256)),
                ('Street_Address_2', models.CharField(blank=True, max_length=256)),
                ('City', models.CharField(max_length=128)),
                ('State', models.CharField(max_length=2)),
                ('Zip5', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=64)),
                ('Provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='physician_data.provider')),
            ],
        ),
    ]
