# Generated by Django 4.0.6 on 2022-07-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarydata',
            name='AFib_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Age_65_74_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Age_75_84_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Age_GT_84_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Age_LT_65_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Alzhmr_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Asthma_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Average_Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Avg_Risk_Score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='COPD_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Cancer_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Depression_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Diabetes_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Drug_Total_Benes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Dual_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Female_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Heart_Failure_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Hyplpdma_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Hyprtnsn_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Ischemic_Heart_Disease_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Kidney_Disease_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Male_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Med_Total_Benes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Not_Dual_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Osteoporosis_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_API_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_Black_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_Hispanic_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_NatInd_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_Other_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Race_White_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Rh_Os_Arthritis_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Schizo_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Stroke_Pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarydata',
            name='Total_Benes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='HCPCS_Codes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Mdcr_Allowed_Amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Mdcr_Payment_Amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Mdcr_Stdzd_Amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Services',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Submitted_Charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Type',
            field=models.CharField(choices=[('Total', 'Total'), ('Drug', 'Drug'), ('Medical', 'Medical')], max_length=16, null=True),
        ),
    ]
