# Generated by Django 4.0.6 on 2022-07-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='physician_data.physician'),
        ),
        migrations.AlterField(
            model_name='beneficiarydata',
            name='Physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_data', to='physician_data.physician'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='physician_data.physician'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='MI',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Middle Initial'),
        ),
    ]
