# Generated by Django 4.0.6 on 2022-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0003_alter_address_street_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='First_Name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
