# Generated by Django 4.0.6 on 2022-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0004_alter_physician_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='Credentials',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='Entity_Type',
            field=models.CharField(choices=[('O', 'Organization'), ('I', 'Individual')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='MPI',
            field=models.CharField(max_length=8, null=True, verbose_name='Medicare Participation Indicator'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='Physician_Type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
