# Generated by Django 4.0.6 on 2022-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician_data', '0005_alter_physician_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='RUCA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='RUCA_Desc',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
